export default [
  {
    path: '//weibo.com/',
    name: 'jeffjade',
    class: 'weibo',
    title: '微博',
    notInQuickapp: true,
  },
  {
    path: '//github.com/',
    name: 'nicejade',
    class: 'github',
    title: 'Github',
  },
  {
    path: '//www.zhihu.com/people/',
    name: 'yang-qiong-pu',
    class: 'zhihu',
    title: '知乎',
    notInQuickapp: true,
  },
  {
    path: '//www.jeffjade.com/',
    name: 'about-me',
    class: 'blog',
    title: '晚晴幽草轩',
  },
  {
    path: '//www.jianshu.com/u/',
    name: '9aae3d8f4c3d',
    class: 'jianshu',
    title: '简书',
    notInQuickapp: true,
  },
  {
    path: '//twitter.com/',
    name: 'nicejadeyang',
    class: 'twitter',
    title: 'Twitter',
    notInMobile: true,
  },
  {
    path: '//www.facebook.com/',
    name: 'nice.jade.yang',
    class: 'facebook',
    title: 'Facebook',
    notInMobile: true,
  },
  {
    path: 'mailto:',
    name: 'yunjeff@163.com',
    class: 'email',
    title: '邮件',
    notInMobile: true,
  },
]
